/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * OpenAPI spec version: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AutoBudgetPeriod } from './auto-budget-period';
import { AutoBudgetType } from './auto-budget-type';
import { BudgetSpent } from './budget-spent';
/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof Budget
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    order?: number;
    /**
     * 
     * @type {AutoBudgetType}
     * @memberof Budget
     */
    autoBudgetType?: AutoBudgetType;
    /**
     * Use either currency_id or currency_code. Defaults to the user's default currency.
     * @type {string}
     * @memberof Budget
     */
    autoBudgetCurrencyId?: string | null;
    /**
     * Use either currency_id or currency_code. Defaults to the user's default currency.
     * @type {string}
     * @memberof Budget
     */
    autoBudgetCurrencyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    autoBudgetAmount?: string | null;
    /**
     * 
     * @type {AutoBudgetPeriod}
     * @memberof Budget
     */
    autoBudgetPeriod?: AutoBudgetPeriod;
    /**
     * Information on how much was spent in this budget. Is only filled in when the start and end date are submitted.
     * @type {Array<BudgetSpent>}
     * @memberof Budget
     */
    spent?: Array<BudgetSpent>;
}
