/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * OpenAPI spec version: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PiggyBank
 */
export interface PiggyBank {
    /**
     * 
     * @type {Date}
     * @memberof PiggyBank
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PiggyBank
     */
    updatedAt?: Date;
    /**
     * The ID of the asset account this piggy bank is connected to.
     * @type {string}
     * @memberof PiggyBank
     */
    accountId: string;
    /**
     * The name of the asset account this piggy bank is connected to.
     * @type {string}
     * @memberof PiggyBank
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    currencyId?: string;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    currencySymbol?: string;
    /**
     * Number of decimals supported by the currency
     * @type {number}
     * @memberof PiggyBank
     */
    currencyDecimalPlaces?: number;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    targetAmount: string | null;
    /**
     * 
     * @type {number}
     * @memberof PiggyBank
     */
    percentage?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    currentAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    leftToSave?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    savePerMonth?: string | null;
    /**
     * The date you started with this piggy bank.
     * @type {Date}
     * @memberof PiggyBank
     */
    startDate?: Date;
    /**
     * The date you intend to finish saving money.
     * @type {Date}
     * @memberof PiggyBank
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PiggyBank
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PiggyBank
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PiggyBank
     */
    notes?: string | null;
    /**
     * The group ID of the group this object is part of. NULL if no group.
     * @type {string}
     * @memberof PiggyBank
     */
    objectGroupId?: string | null;
    /**
     * The order of the group. At least 1, for the highest sorting.
     * @type {number}
     * @memberof PiggyBank
     */
    objectGroupOrder?: number | null;
    /**
     * The name of the group. NULL if no group.
     * @type {string}
     * @memberof PiggyBank
     */
    objectGroupTitle?: string | null;
}
