/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * OpenAPI spec version: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionSplit } from './transaction-split';
/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    updatedAt?: Date;
    /**
     * User ID
     * @type {string}
     * @memberof Transaction
     */
    user?: string;
    /**
     * Title of the transaction if it has been split in more than one piece. Empty otherwise.
     * @type {string}
     * @memberof Transaction
     */
    groupTitle?: string | null;
    /**
     * 
     * @type {Array<TransactionSplit>}
     * @memberof Transaction
     */
    transactions: Array<TransactionSplit>;
}
